services:
  python:
    image: dfdc935de72e
    ports:
      - "5000:5000"
      - "3000:3000"
      - "8000:8000"
  neo4j:
    image: neo4j
    ports: 
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_AUTH=none"
    